name: Cross-Platform Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'client/**'
      - 'requirements.txt'
      - '.github/workflows/cross-platform-test.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'client/**'
      - 'requirements.txt'
      - '.github/workflows/cross-platform-test.yml'
  workflow_dispatch:

jobs:
  test-windows:
    name: Test on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64]
        python-version: ['3.13']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Create logs directory
        run: |
          mkdir client\logs
        continue-on-error: true

      - name: Run tests with coverage
        run: |
          cd client
          python -m pytest -v --cov=src --cov-report=xml --cov-report=term

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./client/coverage.xml
          flags: windows
          name: codecov-umbrella
        if: github.repository == 'your-username/net-manager' && github.event_name != 'pull_request'

  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [x64]
        python-version: ['3.13']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Create logs directory
        run: |
          mkdir -p client/logs
        continue-on-error: true

      - name: Run tests with coverage
        run: |
          cd client
          python -m pytest -v --cov=src --cov-report=xml --cov-report=term

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./client/coverage.xml
          flags: linux
          name: codecov-umbrella
        if: github.repository == 'your-username/net-manager' && github.event_name != 'pull_request'

  test-summary:
    name: Test Summary
    needs: [test-windows, test-linux]
    runs-on: ubuntu-latest
    steps:
      - name: All tests passed
        run: echo "All cross-platform tests completed successfully!"